[package]
name = "file-explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.23.0"
tokio = {version = "1.0", features=["full"]}
futures = "0.3.0"
anyhow = "1.0"
thiserror = "1.0"


